PKUFlyingPig/cs-self-learning

docs/好书推荐.md
- Added a link to EOPL's official site.
- Added two more books for PL (PFPL & SF).
- Associated two books (TAPL & SF) with related PKU courses.
=> Add book recommendations for PL

docs/并行与分布式系统/CS149.md
The old plain-IP link is returning a 301 redirect to the new location.
=> CS149: Update course link

docs/操作系统/MIT6.S081.md
之前的链接是指向博客上的operating system标签的，替换为指向mit6.s081分类的
=> 6.s081 update miigon's blog link

docs/数据结构与算法/CS61B.md
之前的markdown转化成github pages后链接不能点击。
https://csdiy.wiki/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/CS61B/
修改后我尝试了下，现在应该是可以点击了：
https://zhiyuanma2017.github.io/cs-self-learning/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/CS61B/
=> Reformat to show links

docs/编程入门/Duke-Coursera-Intro-C.md
Thanks for the approval of my previous PR!
I found 2 display issues at csdiy.wiki. I'm hopeful that this PR will fix it:
- The hyperlink of course URL is plain text and not clickable
- Comment section should have been a list.
=> format issue at csdiy.wiki: duke coursera C markdown format fix.

docs/软件工程/6031.md
我把MIT 6.031: Software Construction lab 实现代码放在https://github.com/pengzhangzhi/self-taught-CS/tree/main/Software%20Construction
感兴趣的话可以引用下。
see this issue https://github.com/PKUFlyingPig/cs-self-learning/issues/211
=> [ENHANCE] Add assignment code/note link to course MIT 6.031: Software Construction

docs/好书推荐.md
=> [FIX]: 替换失效的《动手学深度学习》的链接

docs/人工智能/CYJ.md
However, there is also [a link to the manual on the official website](http://novel.ict.ac.cn/aics/wjxz/sywd/).
=> [FIX] Replace an invalid link in CYJ.md

docs/编译原理/CS143.en.md
本 PR 中包含新增的对 Stanford CS 143 课程介绍的翻译。
第 19 行处连续出现引号是否不自然存疑：本人不确定叙述书名的合理格式（例如是否使用引号或半角书名号等），愿对此熟悉的各位不吝赐教。
=> [TRANSLATE] Translate Stanford's Compiler Course 

docs/编程入门/CS50.en.md, docs/编程入门/CS50.md
Lastest link of this course: https://cs50.harvard.edu/x/2023/#how-to-take-this-course
=> [UPDATE]Add new course link for CS50

docs/数据科学/Data100.en.md, docs/数据科学/Data100.md
[Prerequisites here](https://ds100.org/)
原文如下：
While we are working to make this class widely accessible we currently require the following (or equivalent) prerequisites:
Foundations of Data Science: [Data 8](http://data8.org/) covers much of the material in Data 100 but at an introductory level. Data8 provides basic exposure to python programming and working with tabular data as well as visualization, statistics, and machine learning.
Computing: The Structure and Interpretation of Computer Programs [CS 61A](http://cs61a.org/) or Computational Structures in Data Science [CS 88](http://cs88-website.github.io/). These courses provide additional background in python programming (e.g., for loops, lambdas, debugging, and complexity) that will enable Data 100 to focus more on the concepts in …
=> [ENHANCE] Fix prerequisites of Data 100.

mkdocs.yml
I noticed footnotes extension didn't add in mkdocs.yml, so in "必学工具/信息检索" the footnote didn't render correctly. I read the [reference site](https://squidfunk.github.io/mkdocs-material/reference/footnotes/) of the material for mkdocs coincidentally.  
and this is my first pull request. I quote a word from TED's presenter to linus torvalds  
>  ***thanks for your contribution to the internet***  
上一次发起pull request 的时候我犯了个错误，就是本地的仓库还停留在老版本上，结果发起pull request 后才注意到对其他地方有些许改动,不得不关闭了那个pull request. 为了避免我的第一次pull request 的commit 留在 git log --all --graph的历史耻辱柱上，我做了一些新手都会做的事情。[missing semester 上那幅漫画](https://xkcd.com/1597/)
=> [CONFIG] Add footnotes markdown extension

docs/必学工具/tools.md
Z-Library 官网专门警示了非官方链接：
因此还是修改更新一下。
[Z-Library – the world’s largest e-book library. Your gateway to knowledge and culture.](https://zlibrary-global.se/)
=> [FIX] fix zlibrary link

docs/CS学习规划.md, docs/深度学习/EECS498-007.en.md, docs/深度学习/EECS498-007.md, mkdocs.yml
This PR introduces the addition of the computer vision course `EECS 498-007` offered by the University of Michigan (UMich), taught by Justin Johnson.
To mention, Justin Johnson is also the main contributor and maintainer of course `CS231N` when he's still pursuing his Ph.D. in Stanford.
Designed with beginners in mind, `EECS 498-007` serves as an excellent resource and hands-on practice for those new to computer vision. The course does not require extensive prerequisites, making it accessible for a wide range of students.
I highly recommend this course to any student harboring an interest in computer vision. Your journey into this fascinating field could very well start here.
=> [COURSE] Add UMich EECS 498-007: Deep Learning for Computer Vision

docs/编程入门/CS61A.en.md, docs/编程入门/CS61A.md
Update the URL to text book. The original link no longer work.
=> [FIX] Fix text book link for CS61A

docs/操作系统/NJUOS.md
=> [FIX] Fix course link for NJU OS

docs/操作系统/MIT6.S081.en.md, docs/操作系统/MIT6.S081.md
原 Xiao Fan (樊潇) 博客链接现在返回 404，更新为新的地址.
=> [FIX] Fix blog link for MIT 6.S081

docs/机器学习/CS229.md
=> [FIX] Fix the course link for CS229

docs/编程入门/Python/CS61A.en.md, docs/编程入门/Python/CS61A.md
对CS61A.md的中英语标点混用做了修复
删除了现在已无法直接访问的原网址
添加了fall2024的课程网站备份和课程作业整合
添加了spring2024的课程视频
=> [ENHANCE]Update CS61A resources

docs/数学进阶/numerical.en.md, docs/数学进阶/numerical.md
修复issue #711 
更新`docs/数学进阶/numerical.md`与`docs/数学进阶/numerical.en.md`中的教材链接
=> [FIX] Fix the textbook link for MIT18.330

docs/并行与分布式系统/CS149.md
Update CMU 15-418 course website and recordings.
Problem: The previous course website and videos are no longer accessible.
Update: Now they have been updated to the [sp18 version of the course](https://www.cs.cmu.edu/afs/cs/academic/class/15418-s18/www/index.html) website and corresponding [videos](https://www.cs.cmu.edu/afs/cs/academic/class/15418-s18/www/schedule.html).
=> [UPDATE] Update CMU 15-418 course website and recordings
