docs/好书推荐.md
利益相关：thu 力学系毕业生，纯自学 CS，目前在做系统类的工作~（不知道隔壁出身能不能参与 pku 自学指南 233）
这里主要加了基本推荐书。下面是推荐的理由：
1. 编程语言推荐书：Essential of Programming Languages (EOPL)
EOPL 是在编程语言领域鼎鼎大名的一本书（甚至和 SICP 齐名？）。主要通过带着读者实现各种不同语言特性的解释器来逐步介绍编程语言领域的一些基本概念。经过我的观察，可能因为分为的影响，国内的同学们大多对编程语言的基本概念都不太了解，EOPL 可以解决很多关于编程语言的疑问，做到不仅知其然，还知其所以然。而且书的篇幅不长，实操性很强（基本就是跟着书一步一步写解释器），亲测非常适合自学~ 几乎没有 prerequisite，可能需要简单配一下 Racket 的环境，并学一下 lisp 是什么。
附知乎讨论：https://www.zhihu.com/question/23014211/answer/23384407
2. 操作系统推荐书：Operating Systems: Three Easy Pieces
推荐这本书主要是因为他整体比较简单，条理也很清楚。根据我个人的经验，在自学过程中，最怕的是一个领域上来就看很厚、过于追求细节或者过于高屋建瓴的书。这本基本上可以给读者一个操作系统在干什么的基本印象，掌握一些常识。在有常识的基础下，就可以让自学的同学更有信心去考虑自己要不要继续扎进操作系统的大坑里头，还是看看别的方向。没有这样的常识补充的话，可能经常会出现 “我操作系统都没学，是不是 xxx 也不能看” 的自我猜疑中...
3. 密码学推荐书：Cryptography Engineering: Design Principles and Practical Applications
理由和上面的 3 …
=> 推荐一些适合自学的系统类书籍

docs/必学工具/tools.md, docs/系统安全/MIT6.858.md, mkdocs.yml
=> add a course mit6.858

docs/好书推荐.md
Architecture of a Database System
=> add a book about database

docs/体系结构/CSAPP.md, docs/数据库系统/15445.md
我不太确定是不是要将《程序员的自我修养》放到CSAPP中，但是他确实是一本作为补充CSAPP第七章的一个非常好的读物。并且十分推荐在读完CSAPP以后（至少是虚拟内存以后）再去读这本书。会让我们对程序从编写到编译，再到运行有一个整体的了解。
=> 为CMU15445和CSAPP添加一些补充

docs/CS学习规划.md, docs/数学基础/6.042J.md, docs/数学基础/The Information Theory, Pattern Recognition, and Neural Networks.md, docs/数据结构与算法/CS106B_CS106X.md, docs/电子基础/Signals and Systems_AVO.md, mkdocs.yml
Update contents about CLI environment construction
Add a few courses including Mathematics, Data Structure and Algorithms, Information Theory and Signals and Systems.
=> Various contents added

docs/必学工具/Docker.md
=> add docker course

docs/并行与分布式系统/MIT6.824.md
很棒的仓库~学这么多课太强啦
我去年开源了实现 6.824 lab 的[文档](https://github.com/OneSizeFitsQuorum/MIT6.824-2021)，受到了一些关注，也帮助到了不少陷入瓶颈期的同学，希望可以帮助到更多人~
=> 6.824 补充学习资料

.editorconfig, .github/workflows/ci.yml, .gitignore, mkdocs.yml, requirements.txt
- Add some configuration to mkdocs
- minify HTML
- git revision date localized
- <img width="436" alt="image" src="https://user-images.githubusercontent.com/38343778/153996828-2c645542-33d6-4e78-9de8-100908ced09a.png">
- Two-color theme
- ...
- Add `.editorconfig` to normalize the format
- ...
You can preview by checking this [link](https://dup4.com/cs-self-learning/).
=> Add some configuration to mkdocs.yml

docs/操作系统/MIT6.S081.md
我之前实现过 xv6-riscv-fall2019 的几个 lab 的实现，并且写了比较详细的解法和扩展内容，同时我使用 Rust 语言重新实现了 xv6-riscv 进行了重新设计，里面的文档对 xv6-riscv 的设计进行了更深入的探讨，希望可以被大佬合并~
=> 6.S081 补充材料

mkdocs.yml, overrides/main.html, requirements.txt
评论功能基于 Discussion 和 [giscus](https://giscus.app/zh-CN)，这样大家可以直接在一个课程的评论区交流组队，不需要在 issue 中辣！
prev: [https://www.bj-yan.top/cs-self-learning/](https://www.bj-yan.top/cs-self-learning/)
=> feat ✨: 添加评论功能

docs/体系结构/CSAPP.md, docs/操作系统/MIT6.S081.md, docs/计算机网络/CS144.md
=> Add some detials

docs/数据结构与算法/CS61B.md
我在学习CS61B时上网搜到的，学习CS61B可能需要的一些资源链接，包含考试习题，答案，视频讲解。
记录在我的 https://github.com/ZhiyuanMa2017/CS61B-sp18  
不知是否合适，希望能帮助到他人。
=> CS61B 添加一些考试题目、解答及讨论资源链接

docs/编程入门/CS50.md
Update links for the 2022 version
=> Update links in CS50.md

README.md, docs/编程入门/Duke-Coursera-Intro-C.md, mkdocs.yml
感谢你的repo，非常好。我从那里发现了UBC的数据库课程，现在正在跟，确实不错。
Coursera上的Duke大学的这个C课程不错，推荐！
=> Added Introductory C from Coursera (Duke). Fixed a link

docs/计算机图形学/CS148.md, docs/计算机图形学/GAMES101.md, docs/计算机图形学/GAMES202.md
想了挺久感觉公开作业答案还是不太道德，所以把仓库改成了private，相信有能力完成的同学不用这个仓库也能完成的，而且也有其他人公开了他们的解法。
=> change my repo from public to private

docs/CS学习规划.md, docs/深度学习/LHY.md, mkdocs.yml
=> Correct naming errors

docs/必学工具/Git.md
=> [Enhance] Add video tutorial for Git

docs/好书推荐.md
Add some books for Compiler and Theoretical Computer Science
=> [BOOKS] Add some books

README.md
=> [README] update the link for chinese-copywriting-guidelines

docs/好书推荐.md
推荐了一本设计模式的书。
新加计算机视觉以及机器人分类和推荐书籍，不知道是否需要
=> [BOOKS] add more books

docs/数据库系统/CS186.md
Latest course website link of UCB CS186
=> [FIX]: update latest link for UCB CS186

docs/Web开发/fullstackopen.md, mkdocs.yml
=> [New Course] University of Helsinki: Full Stack open 2022

docs/index.en.md, docs/编程入门/MIT-Missing-Semester.en.md, mkdocs.yml, requirements.txt, template.en.md
#222 and #216 
[mkdocs-static-i18n](https://github.com/ultrabug/mkdocs-static-i18n)
=> [FEATURE] English version support using mkdocs-static-i18n

docs/Web开发/CS142.en.md, docs/数学基础/information.en.md, docs/数学进阶/6.042J.en.md, docs/电子基础/EE16.en.md, docs/编程入门/CS50.en.md, docs/计算机网络/topdown.en.md, template.en.md
=> [FIX] fix typo for English version

docs/体系结构/N2T.en.md
我们这学期的计算机基础就是以这门课为基础的，我也才刚起步。真的感觉课程设计者用心程度和水平都很高，所以来 pr 个英文版，让更多人能学到这门好课！
另，后附的textbook链接只有中文版，或许我可以pr个英文版pdf（如果不涉及版权的话）
=> [TRANSLATE] translate N2T.en.md

docs/操作系统/MIT6.S081.en.md
Created MIT6.S081.en.md with a translation of MIT6.S081.md.
=> [TRANSLATE] Translated MIT6.S081.md

docs/操作系统/CS162.en.md, docs/机器学习/ML.en.md, docs/软件工程/6031.en.md
=> [FIX] fix typo

docs/CS学习规划.md, docs/必学工具/Scoop.md, mkdocs.yml
=> [TOOLS] Add scoop article in tools

docs/好书推荐.md
- Update the textbook resource with:
1. 计算机视觉方向推荐教材列表
2. 深度学习方向推荐教材列表
3. Computer Networking: A Top-Down Approach
4. Fluid Simulation for Computer Graphics
5. Physically Based Rendering: From Theory To Implementation
6. Real-Time Rendering
7. Multiple View Geometry in Computer Vision
8. Probabilistic Robotics
=> [FEAT]Update the textbook resource

docs/编程入门/CS110L.en.md, docs/编程入门/CS110L.md
=> [UPDATE] Add resources in CS110L

docs/人工智能/CS188.md
=> [UPDATE] Add CS 188 Fall 2022 

overrides/main.html
=> [FEATURE] Dynamic theme change for giscus

overrides/main.html
=> [FIX] Fix giscus dark mode in new page

docs/好书推荐.md
Crafting Interpreters discusses how to implement an interpreter for a programming language, and is great help to understand compiler principle in real-life problems.
=> [BOOKS] Add Crafting Interpreters for compiler principle

docs/必学工具/tools.md
Refer to issue #316 
Since plane URL is not working very well, I also add its Tor location.
=> [FIX] Fix Z-library Link & Add Its Tor Address

docs/index.md
New release [v1.0.1](https://github.com/PKUFlyingPig/cs-self-learning/releases/tag/v1.0.1)
=> [Release] v1.0.1

mkdocs.yml
=> [UPDATE] Add navigations for newly added courses

docs/数学基础/MITLA.en.md, docs/数学基础/MITLA.md
The old URL does not work, I replaced it with a new one
=> [FIX] Fix the cover image for Linear Algebra textbook

docs/编程入门/CS61A.md
=> [UPDATE] Add link for CS61A textbook translation

docs/好书推荐.md
我最近看了这两本书， 这两本书已经有新的版本了， 而且也能很容易搜索到pdf版本。更新一下版本和链接。
=> [BOOKS] Update links for two books

docs/必学工具/Vim.en.md, docs/必学工具/Vim.md
I am a vim user on linux, so I make caps as ctrl & esc on linux. This guide is written by me.
At the same time, I made a little language adjustments according to my preferences.
=> make caps as ctrl & esc

docs/编程入门/MIT-Missing-Semester.md
=> [ENHANCE]Course The Missing Semester Chinese subtitles video group added. The hope of end!

docs/index.md
=> [RELEASE] Update release version in home page

docs/深度学习/CS231.en.md
Re forked and re did the translated file.
=> [TRANSLATE] translate course CS231

docs/数据库系统/15445.en.md, docs/数据库系统/15445.md
This PR mainly does three things in general:
1. Introduces key enhancements to the `CMU 15-445` database systems course content, focusing on updating and expanding the material to include the most recent Spring 2023 version.
2. In line with the course's continual evolution, I have incorporated new and fresh resources to ensure the content remains current and comprehensive.
3. I have also made improvements to the overall formatting of the contents.
=> [UPDATE] Enhancements to CMU 15-445: Incorporating Latest Spring 2023 Content & Relevant Resource and Improved Overall Formatting

docs/编程入门/MIT-Missing-Semester.md
[刘黑黑a](https://space.bilibili.com/518734451)已完成 MIT-Missing-Semester 全部视频的汉化，感谢他的辛勤付出
=> [FIX] Update status for MIT-Missing-Semester Chinese subtitle video

mkdocs.yml
修复 https://github.com/PKUFlyingPig/cs-self-learning/issues/499 提出的搜索功能的bug
=> [FIX] fix search language error in mkdocs.yml

docs/机器学习系统/AICS.en.md, docs/机器学习系统/CMU10-414.en.md, docs/机器学习系统/MLC.en.md, docs/深度学习/CS224n.en.md, docs/深度学习/CS285.en.md, docs/深度学习/LHY.en.md
Complete English version for deep learning folder
=> [TRANSLATE] translate AICS/CMU10-414/MLC/CS224n/CS285 and LHY

docs/操作系统/MIT6.S081.md
添加了我博客的 6.s081 lab 的解析。个人认为相比目前已有的博客的优势是解释更加详细
=> [ENHANCE] Add reference blog for MIT6.S081

docs/编程入门/DeCal.md
=> [UPDATE] Add Bilibili link for DeCal course

docs/必学工具/tools.en.md, docs/必学工具/tools.md
Hello, I adds Cyrilex (regex tester and visualizer) and Mockium (Fake data generator) to programming tools section.
=> [TOOLS] Add some programming tools 

docs/必学工具/tools.en.md, docs/必学工具/tools.md
add free Synergy software which a set of keyboard and mouse controls for multiple computers
=> [TOOLS] Add new tools

docs/index.en.md
=> [FIX] Fix typo in index.en.md

docs/必学工具/Vim.md
xremap is a remap tool for linux, supporting both x11 and wayland.
=> [TOOL] Add remap tool for vim on Linux

docs/必学工具/tools.md
Add SQLable, a collection of database tools, including an SQL formatter and validator, an SQL regex tester, a fake data generator, and database playgrounds.
=> [TOOLS] Add SQLable to tools

mkdocs.yml, requirements.txt
=> [Feat] Open external links in markdown on a new tab

docs/编程入门/Java/MIT 6.092.en.md, docs/编程入门/Java/MIT 6.092.md
增加了我自己对MIT6.092的实现，之前人贡献的资源实现有些不全。
=> [ENHANCE] Add resources for MIT6.092

docs/并行与分布式系统/CS149.en.md, docs/并行与分布式系统/CS149.md
Updated the CS149 recordings link with Stanford's new series published in September
=> [UPDATE] CS149 recordings link

docs/计算机网络/CS144.en.md, docs/计算机网络/CS144.md
This PR mainly refactors/updates the current course introduction/description, and adds some helpful [1] resources.
[1] For some definitions of "helpful".
[2] The translation of the English version powered by [DeepSeek-R1](https://www.deepseek.com/).
=> [Course][Update/Refactor] Refactor Standford CS144 documentation + Add new resources

docs/好书推荐.md
1.Computer Organization and Design RISC-V Edition和Computer Organization and Design: The Hardware/Software Interface 本质上是一本书，这本书有三个版本，最早的MIPS以及后来的ARM，RISC-V，可供选择。
2.深度学习推荐书单添加了“Deep Learnng”深度学习(花书)这本书，虽然英文原著是2016年的出版的，但仍具有很高的参考意义。中文版是2017年出版的，中文版有翻译团队的开源PDF可供阅读。
=> [BOOK] Update book recommendations

docs/编程入门/C/CS50.en.md, docs/编程入门/C/CS50.md
Update the course link of cs50, including Chinese and English edition
=> [UPDATE] Update cs50 course link

docs/编程入门/Python/CS61A.en.md, docs/编程入门/Python/CS61A.md
=> [ENHANCE] Add epub link for CS61A textbook.

docs/人工智能/CS188.md
过早的课程网站已被UCB停止访问。更新为最新一期已结束的课程网站。
=> [UPDATE] Update CS188

docs/编程入门/Rust/cs220.en.md, docs/编程入门/Rust/cs220.md, mkdocs.yml
Added the CS220 course from KAIST, which is talking about Rust. 
Fix https://github.com/PKUFlyingPig/cs-self-learning/pull/553
=> [COURSE] Add KAIST CS220

docs/系统安全/CSE365.en.md, docs/系统安全/CSE365.md
This PR updates the course information for CSE365, including:
- Updating the course website link.
- Adjusting the number of modules and challenges.
- Updating the Discord and email contact information.
These changes reflect the latest updates to the course resources.
=> [UPDATE] Update CSE365

docs/Web开发/CS571.en.md, docs/Web开发/CS571.md
This pull request updates the course description for CS 571 in both the English and Chinese documentation to reflect changes in how users can access a required ID for API requests. The most important changes are as follows:
* [`docs/Web开发/CS571.en.md`](diffhunk://#diff-43cc2ccda7c7fac7f6d9e369eb1321822eb43542ba5aed96ed495e8000fb80fbL19-R19): Updated the instructions for obtaining an ID from requiring an email to the instructor to directly applying for a Badger ID via the official course webpage.
* [`docs/Web开发/CS571.md`](diffhunk://#diff-d33aa1e442134f300b49e7dbe3824a0b4b4652e67e981a034df4d5b86db1174cL19-R19): Revised the Chinese documentation to align with the English version, replacing the email-based ID request process with instructions to apply for a Badger ID on the official course …
=> [UPDATE] Update CS571

docs/体系结构/CS61C.en.md, docs/体系结构/CS61C.md
This PR updates the following resources:
> Course website link
> Recording link
> Assignment materials
> Personal resources (from @InsideEmpire and @RisingUppercut)
All updated resources are bilingual (English and Chinese).
=> [UPDATE] Update CS61C

docs/好书推荐.md
一本很有名但是少有人推荐的os好书，这是我本科的教科书，此书的作者为William Stallings
推荐这本书操作系统的书的理由有
1. 针对考研408的同学来说，这本书前五部分的内容完美涵盖几乎所有os考研大纲的内容(大小点都很全)，非常适合408的考生配套一本辅助书
2. 从历年真题来看，很多点都能在书中找到出处
3. 某道考研机构的os讲义，基本围绕这本书写的，讲义中的大部分插图出自此书
4. 书里很多精美的插图，很适合理解操作系统
5. 这本书是对操作系统的基本概念解释的最清楚精确的一本书
408备考操作系统的同学，本书和csapp搭配食用效果更佳
=> [BOOK] Add an OS book

docs/编译原理/SJTU-Compilers.en.md, docs/编译原理/SJTU-Compilers.md, mkdocs.yml
=> [COURSE] Add SJTU SE3355: Compiler Course

docs/数据结构与算法/CS61B.en.md, docs/数据结构与算法/CS61B.md
- Add SP2021 course website link
- Add Gradescope course code MB7ZPY for public access
- Update both Chinese and English versions
=> [Update] Add SP2021 public access information for CS61B
